stages:
  - primary
  - secondary
  - platforms
  - clients
#  - extras

variables: &base_vars
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: 'ragnarok'
  MYSQL_USER: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  GIT_DEPTH: '3'
  DEBIAN_COMMON_PACKAGES: make autoconf zlib1g-dev libpcre3-dev git python

.prerequisites: &prerequisites
  before_script:
    - echo "Building $CI_BUILD_NAME"
    - uname -a
    - ./tools/ci/retry.sh apt-get update
    - ./tools/ci/retry.sh apt-get install -y -qq $INSTALL_PACKAGES $DEBIAN_COMMON_PACKAGES
#    - ./tools/ci/travis.sh importdb ragnarok ragnarok ragnarok $SQLHOST
#    - ./tools/ci/travis.sh getplugins || true
  services:
    - mysql:latest

.branch_exceptions: &branch_exceptions
  only:
    - branches
  except:
    - rathena
    - coverity_scan

# Compilers

re:clang-6.0:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-6.0 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-6.0 --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:clang-6.0:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-6.0 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-6.0 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:clang-7:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: primary
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-7 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-7 --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:clang-7:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-7 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-7 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

pre_re:clang-8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:unstable
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-8 --enable-debug --enable-Werror --enable-buildbot --disable-renewal
    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:clang-8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:unstable
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-8 --enable-debug --enable-Werror --enable-buildbot
    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:clang-8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:unstable
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: clang-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=clang-8 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

pre_re:gcc-4.8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-4.8 mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build CC=gcc-4.8 --enable-debug --enable-Werror --enable-buildbot --disable-renewal
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-4.8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-4.8 mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build CC=gcc-4.8 --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-4.8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-4.8 mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build CC=gcc-4.8 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-4.9:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-4.9 mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build CC=gcc-4.9 --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-4.9:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-4.9 mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build CC=gcc-4.9 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-6:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: primary
  image: debian:stretch
  services:
    - mariadb:10.1
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-6 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-6 --enable-debug --enable-Werror --enable-buildbot
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-6:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:stretch
  services:
    - mariadb:10.1
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-6 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-6 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-7:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-7 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-7 --enable-debug --enable-Werror --enable-buildbot
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-7:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-7 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-7 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: primary
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-8:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-8_i386:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: primary
  image: i386/debian:stretch
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-8_i386:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: i386/debian:stretch
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-8_sanitize:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:stable
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --disable-manager --enable-sanitize=full
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-8_sanitize:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: debian:stable
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --disable-manager --enable-sanitize=full --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-8_i386_sanitize:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: i386/debian:stretch
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --disable-manager --enable-sanitize=full
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

zero-2018:gcc-8_i386_sanitize:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: clients
  image: i386/debian:stretch
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot --disable-manager --enable-sanitize=full --enable-packetver-zero --enable-packetver=20180511
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:gcc-8_cov:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: secondary
  image: debian:buster
  services:
    - mariadb:10
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc-8 gcovr mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build CC=gcc-8 --enable-debug --enable-Werror --enable-buildbot CFLAGS="-coverage" LDFLAGS="-coverage"
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST
#    - gcovr -r . --gcov-executable=gcov-8 -o gcov_re.txt
#    - gcovr -r . --gcov-executable=gcov-8 --html -o gcov_re.html
#    - cat gcov_re.txt
#  artifacts:
#    paths:
#      - gcov_re.*
#    when: on_success

# Distributions

re:debian-oldstable:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:oldstable
  services:
    - mariadb:10.1
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:debian-stable:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:stable
  services:
    - mariadb:10.3
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:debian-testing:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:testing
  services:
    - mariadb:10.3
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot

re:ubuntu-xenial:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: ubuntu:16.04
  services:
    - mysql:5.7
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

pre_re:ubuntu-bionic:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: ubuntu:18.04
  services:
    - mysql:5.7
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot --disable-renewal
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:ubuntu-bionic:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: ubuntu:18.04
  services:
    - mysql:5.7
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

# SQL servers

re:mysql-5.5:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:jessie
  services:
    - mysql:5.5
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client-5.5 libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mysql-5.6:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:unstable
  services:
    - mysql:5.6
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mysql-5.7:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:unstable
  services:
    - mysql:5.7
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mysql-client-5.7 libmysqlclient-dev
    SQLHOST: mysql
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mariadb-10.0:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:jessie
  services:
    - mariadb:10.0
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client-10.0 libmysqlclient-dev
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mariadb-10.1:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:stretch
  services:
    - mariadb:10.1
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client-10.1 libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mariadb-10.3:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:buster
  services:
    - mariadb:10.3
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client-10.3 libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#   - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:mariadb-latest:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:unstable
  services:
    - mariadb:latest
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client libmariadbclient-dev-compat
    SQLHOST: mariadb
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

re:percona:
  <<: *branch_exceptions
  <<: *prerequisites
  stage: platforms
  image: debian:stretch
  services:
    - percona:latest
  variables:
    <<: *base_vars
    INSTALL_PACKAGES: gcc mariadb-client libmariadbclient-dev-compat
    SQLHOST: percona
  script:
    - ./tools/ci/travis.sh build --enable-debug --enable-Werror --enable-buildbot
#    - ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST
